# The URL the site will be built for
base_url = "https://spirali.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown.highlighting]
# Whether to do syntax highlighting
# Theme can be customised via `theme` or `light_theme`/`dark_theme` (see Zola docs)
theme = "github-dark"
style = "inline"

[extra]
# Put all your custom variables here
katex_enable = true
